CREATE TABLE product (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) DEFAULT NULL
);

CREATE TABLE role (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) DEFAULT NULL
);

CREATE TABLE users (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) DEFAULT NULL,
    password VARCHAR(255) DEFAULT NULL
);

CREATE TABLE users_roles (
    user_id BIGINT NOT NULL,
    roles_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, roles_id),
    CONSTRAINT FK_USERS_ROLES_USER_ID FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT FK_USERS_ROLES_ROLE_ID FOREIGN KEY (roles_id) REFERENCES role(id)
);

INSERT INTO role (name) VALUES('PRODUCT_SELECT');
INSERT INTO role (name) VALUES('PRODUCT_INSERT');
INSERT INTO role (name) VALUES('PRODUCT_UPDATE');
INSERT INTO role (name) VALUES('PRODUCT_DELETE');
INSERT INTO role (name) VALUES('RO_DELETE');